language: python

python:
# We don't actually use the Travis Python, but this keeps it organized.
- "3.5"
- "3.6"

## Run jobs on container-based infrastructure, can be overridden per job
#dist: trusty

#matrix:
#  include:
#    # Extra includes for OSX since python language is not available by default on OSX
#    - os: osx
#      language: generic
#      env: PYTHON_VER=3.5
#    - os: osx
#      language: generic
#      env: PYTHON_VER=3.6
#
#    - os: linux
#      python: 3.5
#      env: PYTHON_VER=3.5
#    - os: linux
#      python: 3.6
#      env: PYTHON_VER=3.6

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

#    # Install the Python environment
#  - source devtools/travis-ci/before_install.sh
#  - python -V

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip pytest pytest-cov
  - source activate test-environment
  - python setup.py install

    # Install pip only modules
  - pip install codecov

  #- conda install --use-local arthritis_proj_demo

script:
  - pytest -v --cov=arthritis_proj tests/

notifications:
    email: false

after_success:
  - codecov
